// <auto-generated />
namespace Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class emailconfirmationtoken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(emailconfirmationtoken));
        
        string IMigrationMetadata.Id
        {
            get { return "201405111813076_email-confirmationtoken"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
